# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: ci

on:
  push:
    branches:    # only for pushes on master
    - master
  pull_request:  # for all PRs regardless of their base branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.6
      uses: actions/setup-java@v1
      with:
        java-version: 1.6

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build + Test
      run: ./gradlew build
